steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/focused-pipe-309806/gagster-web', '.']
Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/focused-pipe-309806/gagster-web']
# Deploy to appengine
# - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  # entrypoint: 'bash'
  # args: ['-c', 'gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy']
# timeout: '1600s'
images:
- gcr.io/focused-pipe-309806/gagster-web
